# Generated by Django 5.1.6 on 2025-04-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_orderitem_unit_price'),
        ('commentapp', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.orderitem'),
        ),
    ]
