# Generated by Django 5.1.6 on 2025-04-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_comment_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='orderitem',
        ),
    ]
