# Generated by Django 5.1.6 on 2025-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='order',
            name='addressname',
            field=models.TextField(default='ไม่ระบุ'),
        ),
    ]
