# Generated by Django 5.1.6 on 2025-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_remove_order_recipient_name_order_addressname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip',
            field=models.ImageField(blank=True, upload_to='orders'),
        ),
    ]
