# Generated by Django 5.1.6 on 2025-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('one_pound_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('two_pound_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('three_pound_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=False)),
                ('hav_dough', models.BooleanField(default=False)),
                ('hav_milk', models.BooleanField(default=False)),
                ('hav_redegg', models.BooleanField(default=False)),
                ('hav_whiteegg', models.BooleanField(default=False)),
                ('hav_butter', models.BooleanField(default=False)),
                ('hav_bakpow', models.BooleanField(default=False)),
                ('hav_vanilla', models.BooleanField(default=False)),
                ('hav_nut', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='products')),
            ],
        ),
    ]
