# Generated by Django 5.1.6 on 2025-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isTrending',
            field=models.BooleanField(default=False),
        ),
    ]
